name: rl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.0
  - pip
  - python=3.9.13
  - pytorch
  - torchaudio
  - torchvision
  - pip:
    - gym
    - humanize
    - hyperopt
    - matplotlib
    - maturin
    - monkeytype
    - numba==0.56.0
    - numpy==1.21.0
    - pandas
    - protobuf
    - psutil
    - pygame
    - pyglet
    - pytorch-lightning
    - pyyaml
    - onnx
    - onnxoptimizer
    - onnxruntime
    - onnxruntime-gpu
    - scikit-image
    - scipy
    - seaborn
    - setuptools==59.5.0
    - tabulate
    - tensorboard
    - torchinfo
    - tqdm
